<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<div data-bind="scope: 'lesson_form'" class="entry-edit form-inline">
    <div data-role="spinner" data-component="lesson_form.lesson_form_data_source" class="admin__form-loading-mask">
        <div class="spinner">
            <span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span>
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>