<?php
/** @var \Overdose\LessonOne\Block\Adminhtml\LessonOne $block */
?>

<div class="admin__data-grid-wrap" data-role="grid-wrapper">
    <div class="admin__data-grid-header">
        <div class="admin__data-grid-header-row">
            <div class="admin__data-grid-header-cell">
                <h1>Lessons List</h1>
            </div>
            <div class="admin__data-grid-header-cell admin__control-support">
                <a href="<?= $block->getUrl('lessonone/lesson/edit') ?>" class="action-secondary">
                    Add Lesson
                </a>
            </div>
        </div>
    </div>


        <table class="data-grid admin__table-primary" data-role="grid">
            <thead>
                <tr>
                <th class="data-grid-th">ID</th>
                <th class="data-grid-th">Title</th>
                <th class="data-grid-th">Content</th>
                <th class="data-grid-th">File Name</th>
                <th class="data-grid-th">File Size (Bytes)</th>
                <th class="data-grid-th">Actions</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($block->getCollection() as $lesson): ?>
                    <tr>
                        <td><?= $block->escapeHtml($lesson->getId()) ?></td>
                        <td><?= $block->escapeHtml($lesson->getTitle()) ?></td>
                        <td><?= $block->escapeHtml($lesson->getContent()) ?></td>
                        <td>
                            <?php if ($lesson->getFileName()): ?>
                                <?= $block->escapeHtml($lesson->getFileName()) ?>
                            <?php else: ?>
                            No file
                            <?php endif; ?>
                        </td>
                        <td>
                            <?php if ($lesson->getFileSize()): ?>
                                <?= $block->escapeHtml($lesson->getFileSize()) ?>
                            <?php else: ?>
                            N/A
                            <?php endif; ?>
                        </td>
                        <td>
                            <a href="<?= $block->getUrl('lessonone/lesson/edit', ['lesson_id' => $lesson->getId()]) ?>">
                            Edit
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
</div>